- name: Deploy Flask App using existing zip
  hosts: n1
  become: yes
  vars:
    app_dir: /opt/flask_app
    flask_user: ubuntu

  tasks:
    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ flask_user }}"
        group: "{{ flask_user }}"
        mode: '0755'

    - name: Copy zip from /tmp
      copy:
        src: /tmp/flask_app.zip
        dest: "{{ app_dir }}/flask_app.zip"
        remote_src: yes 
        owner: "{{ flask_user }}"
        group: "{{ flask_user }}"

    - name: Unzip application
      unarchive:
        src: "{{ app_dir }}/flask_app.zip"
        dest: "{{ app_dir }}"
        remote_src: yes
        owner: "{{ flask_user }}"
        group: "{{ flask_user }}"
        extra_opts: "--strip-components=1"

    - name: Install Python requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"