- name: Install Nginx and Certbot on Ubuntu App Server
  hosts: 172.31.44.87  # Direct IP specification (ensure this matches your server)
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Only update if older than 1 hour

    - name: Install Nginx
      apt:
        name: nginx
        state: latest  # Better than 'present' to ensure security updates
        install_recommends: no  # Skip optional packages

    - name: Ensure Nginx is enabled and running
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Allow 'Nginx Full' in UFW
      ufw:
        rule: allow
        name: 'Nginx Full'
      when: "'ufw' in ansible_facts.packages"  # Only if UFW is installed

    - name: Install Certbot components
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: latest
        update_cache: yes  # Refresh package list before install
      notify:
        - Check Certbot installation

  handlers:
    - name: Check Certbot installation
      command: certbot --version
      register: certbot_version
      changed_when: false
      failed_when: certbot_version.rc != 0