---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Install Certbot and Nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
  become: yes

- name: Create Nginx configuration for the app
  template:
    src: nginx-app.conf.j2
    dest: /etc/nginx/sites-available/flask-app.conf
  become: yes

- name: Enable the site
  file:
    src: /etc/nginx/sites-available/flask-app.conf
    dest: /etc/nginx/sites-enabled/flask-app.conf
    state: link
  become: yes

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: yes

- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: cert_file
  become: yes

- name: Obtain Let's Encrypt certificate
  command: >
    certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos --email {{ email_address }}
  become: yes
  when: not cert_file.stat.exists

- name: Set up auto-renewal cron job
  cron:
    name: "Let's Encrypt renewal"
    job: "certbot renew --quiet --no-self-upgrade"
    hour: "3"
    minute: "30"
    weekday: "1"
  become: yesventorty file
