---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Install Certbot and Nginx plugin
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - certbot
    - python3-certbot-nginx

- name: Allow HTTPS and HTTP through UFW
  ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - 'Nginx Full'
    - 'OpenSSH'

- name: Obtain SSL cert with Certbot
  command: >
    certbot --nginx --non-interactive --agree-tos
    -m ifeomalcollins@gmail.com
    -d yourdomain.com
  notify: reload nginx
